/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateConversation201Response,
  CreateConversationRequest,
  CreateMessage201Response,
  CreateMessageRequest,
  DeleteConversation200Response,
  ErrorResponse,
  GetConversation200Response,
  ListConversations200Response,
  UpdateConversationRequest,
  UpdateMessageRequest,
} from '../models/index';
import {
    CreateConversation201ResponseFromJSON,
    CreateConversation201ResponseToJSON,
    CreateConversationRequestFromJSON,
    CreateConversationRequestToJSON,
    CreateMessage201ResponseFromJSON,
    CreateMessage201ResponseToJSON,
    CreateMessageRequestFromJSON,
    CreateMessageRequestToJSON,
    DeleteConversation200ResponseFromJSON,
    DeleteConversation200ResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetConversation200ResponseFromJSON,
    GetConversation200ResponseToJSON,
    ListConversations200ResponseFromJSON,
    ListConversations200ResponseToJSON,
    UpdateConversationRequestFromJSON,
    UpdateConversationRequestToJSON,
    UpdateMessageRequestFromJSON,
    UpdateMessageRequestToJSON,
} from '../models/index';

export interface CreateConversationOperationRequest {
    createConversationRequest?: CreateConversationRequest;
}

export interface CreateMessageOperationRequest {
    conversationId: string;
    createMessageRequest: CreateMessageRequest;
}

export interface DeleteConversationRequest {
    conversationId: string;
}

export interface DeleteMessageRequest {
    conversationId: string;
    messageId: string;
}

export interface GetConversationRequest {
    conversationId: string;
}

export interface UpdateConversationOperationRequest {
    conversationId: string;
    updateConversationRequest: UpdateConversationRequest;
}

export interface UpdateMessageOperationRequest {
    conversationId: string;
    messageId: string;
    updateMessageRequest: UpdateMessageRequest;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Create a new conversation
     */
    async createConversationRaw(requestParameters: CreateConversationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateConversation201Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/conversations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateConversationRequestToJSON(requestParameters['createConversationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateConversation201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new conversation
     */
    async createConversation(requestParameters: CreateConversationOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateConversation201Response> {
        const response = await this.createConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a message to a conversation
     */
    async createMessageRaw(requestParameters: CreateMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateMessage201Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling createMessage().'
            );
        }

        if (requestParameters['createMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'createMessageRequest',
                'Required parameter "createMessageRequest" was null or undefined when calling createMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/conversations/{conversationId}/messages`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMessageRequestToJSON(requestParameters['createMessageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateMessage201ResponseFromJSON(jsonValue));
    }

    /**
     * Add a message to a conversation
     */
    async createMessage(requestParameters: CreateMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateMessage201Response> {
        const response = await this.createMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a conversation and all its messages
     */
    async deleteConversationRaw(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteConversation200Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling deleteConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/conversations/{conversationId}`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteConversation200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a conversation and all its messages
     */
    async deleteConversation(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteConversation200Response> {
        const response = await this.deleteConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a single message
     */
    async deleteMessageRaw(requestParameters: DeleteMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteConversation200Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling deleteMessage().'
            );
        }

        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling deleteMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/conversations/{conversationId}/messages/{messageId}`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))).replace(`{${"messageId"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteConversation200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a single message
     */
    async deleteMessage(requestParameters: DeleteMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteConversation200Response> {
        const response = await this.deleteMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a conversation with all its messages
     */
    async getConversationRaw(requestParameters: GetConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetConversation200Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/conversations/{conversationId}`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetConversation200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a conversation with all its messages
     */
    async getConversation(requestParameters: GetConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetConversation200Response> {
        const response = await this.getConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all conversations ordered newest first. Messages are not included.
     * List all conversations
     */
    async listConversationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListConversations200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chat/conversations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListConversations200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all conversations ordered newest first. Messages are not included.
     * List all conversations
     */
    async listConversations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListConversations200Response> {
        const response = await this.listConversationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a conversation\'s title or profile
     */
    async updateConversationRaw(requestParameters: UpdateConversationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateConversation201Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversation().'
            );
        }

        if (requestParameters['updateConversationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateConversationRequest',
                'Required parameter "updateConversationRequest" was null or undefined when calling updateConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/conversations/{conversationId}`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateConversationRequestToJSON(requestParameters['updateConversationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateConversation201ResponseFromJSON(jsonValue));
    }

    /**
     * Update a conversation\'s title or profile
     */
    async updateConversation(requestParameters: UpdateConversationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateConversation201Response> {
        const response = await this.updateConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a message\'s content
     */
    async updateMessageRaw(requestParameters: UpdateMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateMessage201Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateMessage().'
            );
        }

        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling updateMessage().'
            );
        }

        if (requestParameters['updateMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMessageRequest',
                'Required parameter "updateMessageRequest" was null or undefined when calling updateMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/chat/conversations/{conversationId}/messages/{messageId}`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))).replace(`{${"messageId"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMessageRequestToJSON(requestParameters['updateMessageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateMessage201ResponseFromJSON(jsonValue));
    }

    /**
     * Edit a message\'s content
     */
    async updateMessage(requestParameters: UpdateMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateMessage201Response> {
        const response = await this.updateMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
