/**
 * Run context — mutable state container for a single Agent.run() execution.
 *
 * WHY: Pulls all the "state variables" of a run into one object,
 * so the main loop doesn't juggle 15+ local variables.
 * Each helper method reads/writes this shared state cleanly.
 *
 * PATTERN: Created at the start of `run()`, passed to helper functions.
 *
 * @module agent/run-context
 */

import type { ModelProfile } from './model-router';
import type { IDiagnosticEntry } from '../diagnostics';
import type { IToolCall } from '../persistence/types';
import type { IToolCitation } from '../tools/citations';
import { ToolCitationBuffer } from '../tools/citations';
import { ToolCallDeduplicator } from '../tools/tool-call-deduplicator';
import { randomUUID } from 'node:crypto';

/**
 * Mutable token counters accumulated across LLM steps.
 */
export interface ITokenAccumulator {
    promptTokens: number | undefined;
    completionTokens: number | undefined;
}

/**
 * Structured metadata produced by one Agent.run() execution.
 */
export interface IAgentRunMeta {
    /** ISO timestamp indicating when this run started. */
    startedAt: string;
    /** Wall-clock duration in milliseconds for the full run. */
    durationMs: number;
    /** Number of LLM reasoning steps executed. */
    steps: number;
    /** Number of tool calls executed (success + failure). */
    toolCalls: number;
    /** Models used by this run (deduplicated, execution order preserved). */
    models: string[];
    /** Effective profile when a single profile is identifiable. */
    profile?: ModelProfile;
    /** Aggregated prompt tokens when reported by the provider. */
    promptTokens?: number;
    /** Aggregated completion tokens when reported by the provider. */
    completionTokens?: number;
    /** Aggregated total tokens when both prompt/completion totals are known. */
    totalTokens?: number;
    /** Final context length in characters. */
    contextLength: number;
    /** Whether semantic memory retrieval returned entries. */
    memoryUsed: boolean;
    /** Citations collected from tool outputs during this run. */
    citations: IToolCitation[];
}

/**
 * Full result returned by Agent.run().
 */
export interface IAgentRunResult {
    /** Final answer generated by the agent loop. */
    answer: string;
    /** Operational metadata captured during the run. */
    meta: IAgentRunMeta;
    /** Citations collected from tool outputs during this run. */
    citations: IToolCitation[];
}

/**
 * Mutable run state — one instance per Agent.run() invocation.
 *
 * Groups timers, accumulators, and diagnostic buffers so
 * helper functions can read/write without juggling parameters.
 */
export class RunContext {
    /** Unique identifier for this run (for events and persistence). */
    readonly runId: string;
    /** Wall-clock start timestamp (epoch ms). */
    readonly runStartedAt: number;
    /** Start time as Date (used for persistence). */
    readonly startTime: Date;

    /** Accumulated conversation context (tool results, feedback). */
    context = '';
    /** Base64 images queued for the next multimodal LLM call. */
    pendingImages: string[] = [];
    /** Diagnostic log entries collected during the run. */
    readonly diagnosticEntries: IDiagnosticEntry[] = [];
    /** Tool call records (for persistence and metadata). */
    readonly toolCalls: IToolCall[] = [];
    /** Prevents repeated identical tool calls. */
    readonly toolDeduplicator = new ToolCallDeduplicator();
    /** Accumulates citations from tool results. */
    readonly citationBuffer = new ToolCitationBuffer();
    /** Tracks which models were used (deduplicates). */
    readonly modelsUsed = new Set<string>();
    /** Tracks which profiles were used. */
    readonly profilesUsed = new Set<ModelProfile>();
    /** Token counters accumulated across LLM steps. */
    readonly tokens: ITokenAccumulator = { promptTokens: undefined, completionTokens: undefined };
    /** Number of LLM calls made during this run. */
    llmSteps = 0;

    constructor() {
        this.runId = randomUUID();
        this.runStartedAt = Date.now();
        this.startTime = new Date();
    }

    /** Elapsed time since run start (ms). */
    get elapsedMs(): number {
        return Date.now() - this.runStartedAt;
    }

    /**
     * Build the IAgentRunMeta snapshot for the current run state.
     *
     * @param forcedProfile - Profile forced by the caller (overrides auto-detection).
     * @param citations     - Optionally override citations (e.g. after flush).
     */
    buildRunMeta(forcedProfile?: ModelProfile, citations?: IToolCitation[]): IAgentRunMeta {
        const usedCitations = citations ?? this.citationBuffer.peek();
        const totalTokens =
            typeof this.tokens.promptTokens === 'number' &&
            typeof this.tokens.completionTokens === 'number'
                ? this.tokens.promptTokens + this.tokens.completionTokens
                : undefined;
        const profile =
            forcedProfile ??
            (this.profilesUsed.size === 1 ? [...this.profilesUsed][0] : undefined);
        return {
            startedAt: this.startTime.toISOString(),
            durationMs: this.elapsedMs,
            steps: this.llmSteps,
            toolCalls: this.toolCalls.length,
            models: [...this.modelsUsed],
            profile,
            promptTokens: this.tokens.promptTokens,
            completionTokens: this.tokens.completionTokens,
            totalTokens,
            contextLength: this.context.length,
            memoryUsed: false, // set by caller after memory load
            citations: usedCitations
        };
    }
}
