/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface ConversationWithMessages
 */
export interface ConversationWithMessages {
    /**
     * 
     * @type {string}
     * @memberof ConversationWithMessages
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationWithMessages
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationWithMessages
     */
    profile?: ConversationWithMessagesProfileEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof ConversationWithMessages
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConversationWithMessages
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof ConversationWithMessages
     */
    messages: Array<ChatMessage>;
}


/**
 * @export
 */
export const ConversationWithMessagesProfileEnum = {
    Fast: 'fast',
    Reasoning: 'reasoning',
    Code: 'code'
} as const;
export type ConversationWithMessagesProfileEnum = typeof ConversationWithMessagesProfileEnum[keyof typeof ConversationWithMessagesProfileEnum];


/**
 * Check if a given object implements the ConversationWithMessages interface.
 */
export function instanceOfConversationWithMessages(value: object): value is ConversationWithMessages {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ConversationWithMessagesFromJSON(json: any): ConversationWithMessages {
    return ConversationWithMessagesFromJSONTyped(json, false);
}

export function ConversationWithMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationWithMessages {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'messages': ((json['messages'] as Array<any>).map(ChatMessageFromJSON)),
    };
}

  export function ConversationWithMessagesToJSON(json: any): ConversationWithMessages {
      return ConversationWithMessagesToJSONTyped(json, false);
  }

  export function ConversationWithMessagesToJSONTyped(value?: ConversationWithMessages | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'profile': value['profile'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'messages': ((value['messages'] as Array<any>).map(ChatMessageToJSON)),
    };
}

