/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConversationRequest
 */
export interface CreateConversationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateConversationRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateConversationRequest
     */
    profile?: CreateConversationRequestProfileEnum | null;
}


/**
 * @export
 */
export const CreateConversationRequestProfileEnum = {
    Fast: 'fast',
    Reasoning: 'reasoning',
    Code: 'code'
} as const;
export type CreateConversationRequestProfileEnum = typeof CreateConversationRequestProfileEnum[keyof typeof CreateConversationRequestProfileEnum];


/**
 * Check if a given object implements the CreateConversationRequest interface.
 */
export function instanceOfCreateConversationRequest(value: object): value is CreateConversationRequest {
    return true;
}

export function CreateConversationRequestFromJSON(json: any): CreateConversationRequest {
    return CreateConversationRequestFromJSONTyped(json, false);
}

export function CreateConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'profile': json['profile'] == null ? undefined : json['profile'],
    };
}

  export function CreateConversationRequestToJSON(json: any): CreateConversationRequest {
      return CreateConversationRequestToJSONTyped(json, false);
  }

  export function CreateConversationRequestToJSONTyped(value?: CreateConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'profile': value['profile'],
    };
}

