/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { CreateConversation201ResponseAllOfData } from './CreateConversation201ResponseAllOfData';
import {
    CreateConversation201ResponseAllOfDataFromJSON,
    CreateConversation201ResponseAllOfDataFromJSONTyped,
    CreateConversation201ResponseAllOfDataToJSON,
    CreateConversation201ResponseAllOfDataToJSONTyped,
} from './CreateConversation201ResponseAllOfData';

/**
 * 
 * @export
 * @interface CreateConversation201Response
 */
export interface CreateConversation201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateConversation201Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateConversation201Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CreateConversation201Response
     */
    message: string;
    /**
     * 
     * @type {CreateConversation201ResponseAllOfData}
     * @memberof CreateConversation201Response
     */
    data?: CreateConversation201ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof CreateConversation201Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the CreateConversation201Response interface.
 */
export function instanceOfCreateConversation201Response(value: object): value is CreateConversation201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateConversation201ResponseFromJSON(json: any): CreateConversation201Response {
    return CreateConversation201ResponseFromJSONTyped(json, false);
}

export function CreateConversation201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversation201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : CreateConversation201ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function CreateConversation201ResponseToJSON(json: any): CreateConversation201Response {
      return CreateConversation201ResponseToJSONTyped(json, false);
  }

  export function CreateConversation201ResponseToJSONTyped(value?: CreateConversation201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': CreateConversation201ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

