/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMessage201ResponseAllOfData } from './CreateMessage201ResponseAllOfData';
import {
    CreateMessage201ResponseAllOfDataFromJSON,
    CreateMessage201ResponseAllOfDataFromJSONTyped,
    CreateMessage201ResponseAllOfDataToJSON,
    CreateMessage201ResponseAllOfDataToJSONTyped,
} from './CreateMessage201ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface CreateMessage201Response
 */
export interface CreateMessage201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateMessage201Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateMessage201Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CreateMessage201Response
     */
    message: string;
    /**
     * 
     * @type {CreateMessage201ResponseAllOfData}
     * @memberof CreateMessage201Response
     */
    data?: CreateMessage201ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof CreateMessage201Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the CreateMessage201Response interface.
 */
export function instanceOfCreateMessage201Response(value: object): value is CreateMessage201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateMessage201ResponseFromJSON(json: any): CreateMessage201Response {
    return CreateMessage201ResponseFromJSONTyped(json, false);
}

export function CreateMessage201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessage201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : CreateMessage201ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function CreateMessage201ResponseToJSON(json: any): CreateMessage201Response {
      return CreateMessage201ResponseToJSONTyped(json, false);
  }

  export function CreateMessage201ResponseToJSONTyped(value?: CreateMessage201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': CreateMessage201ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

