/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface CreateMessage201ResponseAllOfData
 */
export interface CreateMessage201ResponseAllOfData {
    /**
     * 
     * @type {ChatMessage}
     * @memberof CreateMessage201ResponseAllOfData
     */
    message?: ChatMessage;
}

/**
 * Check if a given object implements the CreateMessage201ResponseAllOfData interface.
 */
export function instanceOfCreateMessage201ResponseAllOfData(value: object): value is CreateMessage201ResponseAllOfData {
    return true;
}

export function CreateMessage201ResponseAllOfDataFromJSON(json: any): CreateMessage201ResponseAllOfData {
    return CreateMessage201ResponseAllOfDataFromJSONTyped(json, false);
}

export function CreateMessage201ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessage201ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : ChatMessageFromJSON(json['message']),
    };
}

  export function CreateMessage201ResponseAllOfDataToJSON(json: any): CreateMessage201ResponseAllOfData {
      return CreateMessage201ResponseAllOfDataToJSONTyped(json, false);
  }

  export function CreateMessage201ResponseAllOfDataToJSONTyped(value?: CreateMessage201ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': ChatMessageToJSON(value['message']),
    };
}

