/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Conversation } from './Conversation';
import {
    ConversationFromJSON,
    ConversationFromJSONTyped,
    ConversationToJSON,
    ConversationToJSONTyped,
} from './Conversation';

/**
 * 
 * @export
 * @interface CreateConversation201ResponseAllOfData
 */
export interface CreateConversation201ResponseAllOfData {
    /**
     * 
     * @type {Conversation}
     * @memberof CreateConversation201ResponseAllOfData
     */
    conversation?: Conversation;
}

/**
 * Check if a given object implements the CreateConversation201ResponseAllOfData interface.
 */
export function instanceOfCreateConversation201ResponseAllOfData(value: object): value is CreateConversation201ResponseAllOfData {
    return true;
}

export function CreateConversation201ResponseAllOfDataFromJSON(json: any): CreateConversation201ResponseAllOfData {
    return CreateConversation201ResponseAllOfDataFromJSONTyped(json, false);
}

export function CreateConversation201ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversation201ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'conversation': json['conversation'] == null ? undefined : ConversationFromJSON(json['conversation']),
    };
}

  export function CreateConversation201ResponseAllOfDataToJSON(json: any): CreateConversation201ResponseAllOfData {
      return CreateConversation201ResponseAllOfDataToJSONTyped(json, false);
  }

  export function CreateConversation201ResponseAllOfDataToJSONTyped(value?: CreateConversation201ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation': ConversationToJSON(value['conversation']),
    };
}

