/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeleteConversation200ResponseAllOfData } from './DeleteConversation200ResponseAllOfData';
import {
    DeleteConversation200ResponseAllOfDataFromJSON,
    DeleteConversation200ResponseAllOfDataFromJSONTyped,
    DeleteConversation200ResponseAllOfDataToJSON,
    DeleteConversation200ResponseAllOfDataToJSONTyped,
} from './DeleteConversation200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface DeleteConversation200Response
 */
export interface DeleteConversation200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteConversation200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof DeleteConversation200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof DeleteConversation200Response
     */
    message: string;
    /**
     * 
     * @type {DeleteConversation200ResponseAllOfData}
     * @memberof DeleteConversation200Response
     */
    data?: DeleteConversation200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof DeleteConversation200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the DeleteConversation200Response interface.
 */
export function instanceOfDeleteConversation200Response(value: object): value is DeleteConversation200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteConversation200ResponseFromJSON(json: any): DeleteConversation200Response {
    return DeleteConversation200ResponseFromJSONTyped(json, false);
}

export function DeleteConversation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteConversation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : DeleteConversation200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function DeleteConversation200ResponseToJSON(json: any): DeleteConversation200Response {
      return DeleteConversation200ResponseToJSONTyped(json, false);
  }

  export function DeleteConversation200ResponseToJSONTyped(value?: DeleteConversation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': DeleteConversation200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

