/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteConversation200ResponseAllOfData
 */
export interface DeleteConversation200ResponseAllOfData {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteConversation200ResponseAllOfData
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the DeleteConversation200ResponseAllOfData interface.
 */
export function instanceOfDeleteConversation200ResponseAllOfData(value: object): value is DeleteConversation200ResponseAllOfData {
    return true;
}

export function DeleteConversation200ResponseAllOfDataFromJSON(json: any): DeleteConversation200ResponseAllOfData {
    return DeleteConversation200ResponseAllOfDataFromJSONTyped(json, false);
}

export function DeleteConversation200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteConversation200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

  export function DeleteConversation200ResponseAllOfDataToJSON(json: any): DeleteConversation200ResponseAllOfData {
      return DeleteConversation200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function DeleteConversation200ResponseAllOfDataToJSONTyped(value?: DeleteConversation200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

