/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleExport } from './ArticleExport';
import {
    ArticleExportFromJSON,
    ArticleExportFromJSONTyped,
    ArticleExportToJSON,
    ArticleExportToJSONTyped,
} from './ArticleExport';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ExportLibrary200Response
 */
export interface ExportLibrary200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ExportLibrary200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExportLibrary200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ExportLibrary200Response
     */
    message: string;
    /**
     * 
     * @type {Array<ArticleExport>}
     * @memberof ExportLibrary200Response
     */
    data?: Array<ArticleExport>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ExportLibrary200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the ExportLibrary200Response interface.
 */
export function instanceOfExportLibrary200Response(value: object): value is ExportLibrary200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ExportLibrary200ResponseFromJSON(json: any): ExportLibrary200Response {
    return ExportLibrary200ResponseFromJSONTyped(json, false);
}

export function ExportLibrary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportLibrary200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ArticleExportFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function ExportLibrary200ResponseToJSON(json: any): ExportLibrary200Response {
      return ExportLibrary200ResponseToJSONTyped(json, false);
  }

  export function ExportLibrary200ResponseToJSONTyped(value?: ExportLibrary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ArticleExportToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

