/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationWithMessages } from './ConversationWithMessages';
import {
    ConversationWithMessagesFromJSON,
    ConversationWithMessagesFromJSONTyped,
    ConversationWithMessagesToJSON,
    ConversationWithMessagesToJSONTyped,
} from './ConversationWithMessages';

/**
 * 
 * @export
 * @interface GetConversation200ResponseAllOfData
 */
export interface GetConversation200ResponseAllOfData {
    /**
     * 
     * @type {ConversationWithMessages}
     * @memberof GetConversation200ResponseAllOfData
     */
    conversation?: ConversationWithMessages;
}

/**
 * Check if a given object implements the GetConversation200ResponseAllOfData interface.
 */
export function instanceOfGetConversation200ResponseAllOfData(value: object): value is GetConversation200ResponseAllOfData {
    return true;
}

export function GetConversation200ResponseAllOfDataFromJSON(json: any): GetConversation200ResponseAllOfData {
    return GetConversation200ResponseAllOfDataFromJSONTyped(json, false);
}

export function GetConversation200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversation200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'conversation': json['conversation'] == null ? undefined : ConversationWithMessagesFromJSON(json['conversation']),
    };
}

  export function GetConversation200ResponseAllOfDataToJSON(json: any): GetConversation200ResponseAllOfData {
      return GetConversation200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function GetConversation200ResponseAllOfDataToJSONTyped(value?: GetConversation200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation': ConversationWithMessagesToJSON(value['conversation']),
    };
}

