/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConversation200ResponseAllOfData } from './GetConversation200ResponseAllOfData';
import {
    GetConversation200ResponseAllOfDataFromJSON,
    GetConversation200ResponseAllOfDataFromJSONTyped,
    GetConversation200ResponseAllOfDataToJSON,
    GetConversation200ResponseAllOfDataToJSONTyped,
} from './GetConversation200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface GetConversation200Response
 */
export interface GetConversation200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetConversation200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetConversation200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetConversation200Response
     */
    message: string;
    /**
     * 
     * @type {GetConversation200ResponseAllOfData}
     * @memberof GetConversation200Response
     */
    data?: GetConversation200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetConversation200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetConversation200Response interface.
 */
export function instanceOfGetConversation200Response(value: object): value is GetConversation200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetConversation200ResponseFromJSON(json: any): GetConversation200Response {
    return GetConversation200ResponseFromJSONTyped(json, false);
}

export function GetConversation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : GetConversation200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetConversation200ResponseToJSON(json: any): GetConversation200Response {
      return GetConversation200ResponseToJSONTyped(json, false);
  }

  export function GetConversation200ResponseToJSONTyped(value?: GetConversation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': GetConversation200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

