/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHelp200ResponseAllOfDataEndpointsInnerParamsInner } from './GetHelp200ResponseAllOfDataEndpointsInnerParamsInner';
import {
    GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerFromJSON,
    GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerFromJSONTyped,
    GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerToJSON,
    GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerToJSONTyped,
} from './GetHelp200ResponseAllOfDataEndpointsInnerParamsInner';

/**
 * 
 * @export
 * @interface GetHelp200ResponseAllOfDataEndpointsInner
 */
export interface GetHelp200ResponseAllOfDataEndpointsInner {
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInner
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInner
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInner
     */
    summary?: string;
    /**
     * 
     * @type {Array<GetHelp200ResponseAllOfDataEndpointsInnerParamsInner>}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInner
     */
    params?: Array<GetHelp200ResponseAllOfDataEndpointsInnerParamsInner>;
}

/**
 * Check if a given object implements the GetHelp200ResponseAllOfDataEndpointsInner interface.
 */
export function instanceOfGetHelp200ResponseAllOfDataEndpointsInner(value: object): value is GetHelp200ResponseAllOfDataEndpointsInner {
    return true;
}

export function GetHelp200ResponseAllOfDataEndpointsInnerFromJSON(json: any): GetHelp200ResponseAllOfDataEndpointsInner {
    return GetHelp200ResponseAllOfDataEndpointsInnerFromJSONTyped(json, false);
}

export function GetHelp200ResponseAllOfDataEndpointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHelp200ResponseAllOfDataEndpointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'] == null ? undefined : json['method'],
        'path': json['path'] == null ? undefined : json['path'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'params': json['params'] == null ? undefined : ((json['params'] as Array<any>).map(GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerFromJSON)),
    };
}

  export function GetHelp200ResponseAllOfDataEndpointsInnerToJSON(json: any): GetHelp200ResponseAllOfDataEndpointsInner {
      return GetHelp200ResponseAllOfDataEndpointsInnerToJSONTyped(json, false);
  }

  export function GetHelp200ResponseAllOfDataEndpointsInnerToJSONTyped(value?: GetHelp200ResponseAllOfDataEndpointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'path': value['path'],
        'summary': value['summary'],
        'params': value['params'] == null ? undefined : ((value['params'] as Array<any>).map(GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerToJSON)),
    };
}

