/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHelp200ResponseAllOfDataEndpointsInnerParamsInner
 */
export interface GetHelp200ResponseAllOfDataEndpointsInnerParamsInner {
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInnerParamsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInnerParamsInner
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInnerParamsInner
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfDataEndpointsInnerParamsInner
     */
    description?: string;
}

/**
 * Check if a given object implements the GetHelp200ResponseAllOfDataEndpointsInnerParamsInner interface.
 */
export function instanceOfGetHelp200ResponseAllOfDataEndpointsInnerParamsInner(value: object): value is GetHelp200ResponseAllOfDataEndpointsInnerParamsInner {
    return true;
}

export function GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerFromJSON(json: any): GetHelp200ResponseAllOfDataEndpointsInnerParamsInner {
    return GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerFromJSONTyped(json, false);
}

export function GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHelp200ResponseAllOfDataEndpointsInnerParamsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'required': json['required'] == null ? undefined : json['required'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

  export function GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerToJSON(json: any): GetHelp200ResponseAllOfDataEndpointsInnerParamsInner {
      return GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerToJSONTyped(json, false);
  }

  export function GetHelp200ResponseAllOfDataEndpointsInnerParamsInnerToJSONTyped(value?: GetHelp200ResponseAllOfDataEndpointsInnerParamsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'required': value['required'],
        'description': value['description'],
    };
}

