/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { HealthResponse } from './HealthResponse';
import {
    HealthResponseFromJSON,
    HealthResponseFromJSONTyped,
    HealthResponseToJSON,
    HealthResponseToJSONTyped,
} from './HealthResponse';

/**
 * 
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetHealth200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetHealth200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetHealth200Response
     */
    message: string;
    /**
     * 
     * @type {HealthResponse}
     * @memberof GetHealth200Response
     */
    data?: HealthResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetHealth200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetHealth200Response interface.
 */
export function instanceOfGetHealth200Response(value: object): value is GetHealth200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetHealth200ResponseFromJSON(json: any): GetHealth200Response {
    return GetHealth200ResponseFromJSONTyped(json, false);
}

export function GetHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : HealthResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetHealth200ResponseToJSON(json: any): GetHealth200Response {
      return GetHealth200ResponseToJSONTyped(json, false);
  }

  export function GetHealth200ResponseToJSONTyped(value?: GetHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': HealthResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

