/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHelp200ResponseAllOfData } from './GetHelp200ResponseAllOfData';
import {
    GetHelp200ResponseAllOfDataFromJSON,
    GetHelp200ResponseAllOfDataFromJSONTyped,
    GetHelp200ResponseAllOfDataToJSON,
    GetHelp200ResponseAllOfDataToJSONTyped,
} from './GetHelp200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface GetHelp200Response
 */
export interface GetHelp200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetHelp200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetHelp200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200Response
     */
    message: string;
    /**
     * 
     * @type {GetHelp200ResponseAllOfData}
     * @memberof GetHelp200Response
     */
    data?: GetHelp200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetHelp200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetHelp200Response interface.
 */
export function instanceOfGetHelp200Response(value: object): value is GetHelp200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetHelp200ResponseFromJSON(json: any): GetHelp200Response {
    return GetHelp200ResponseFromJSONTyped(json, false);
}

export function GetHelp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHelp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : GetHelp200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetHelp200ResponseToJSON(json: any): GetHelp200Response {
      return GetHelp200ResponseToJSONTyped(json, false);
  }

  export function GetHelp200ResponseToJSONTyped(value?: GetHelp200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': GetHelp200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

