/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHelp200ResponseAllOfDataEndpointsInner } from './GetHelp200ResponseAllOfDataEndpointsInner';
import {
    GetHelp200ResponseAllOfDataEndpointsInnerFromJSON,
    GetHelp200ResponseAllOfDataEndpointsInnerFromJSONTyped,
    GetHelp200ResponseAllOfDataEndpointsInnerToJSON,
    GetHelp200ResponseAllOfDataEndpointsInnerToJSONTyped,
} from './GetHelp200ResponseAllOfDataEndpointsInner';

/**
 * 
 * @export
 * @interface GetHelp200ResponseAllOfData
 */
export interface GetHelp200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseAllOfData
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof GetHelp200ResponseAllOfData
     */
    endpointCount?: number;
    /**
     * 
     * @type {Array<GetHelp200ResponseAllOfDataEndpointsInner>}
     * @memberof GetHelp200ResponseAllOfData
     */
    endpoints?: Array<GetHelp200ResponseAllOfDataEndpointsInner>;
}

/**
 * Check if a given object implements the GetHelp200ResponseAllOfData interface.
 */
export function instanceOfGetHelp200ResponseAllOfData(value: object): value is GetHelp200ResponseAllOfData {
    return true;
}

export function GetHelp200ResponseAllOfDataFromJSON(json: any): GetHelp200ResponseAllOfData {
    return GetHelp200ResponseAllOfDataFromJSONTyped(json, false);
}

export function GetHelp200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHelp200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'endpointCount': json['endpointCount'] == null ? undefined : json['endpointCount'],
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(GetHelp200ResponseAllOfDataEndpointsInnerFromJSON)),
    };
}

  export function GetHelp200ResponseAllOfDataToJSON(json: any): GetHelp200ResponseAllOfData {
      return GetHelp200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function GetHelp200ResponseAllOfDataToJSONTyped(value?: GetHelp200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'endpointCount': value['endpointCount'],
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(GetHelp200ResponseAllOfDataEndpointsInnerToJSON)),
    };
}

