/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetInfoModes200ResponseAllOfDataModesInner } from './GetInfoModes200ResponseAllOfDataModesInner';
import {
    GetInfoModes200ResponseAllOfDataModesInnerFromJSON,
    GetInfoModes200ResponseAllOfDataModesInnerFromJSONTyped,
    GetInfoModes200ResponseAllOfDataModesInnerToJSON,
    GetInfoModes200ResponseAllOfDataModesInnerToJSONTyped,
} from './GetInfoModes200ResponseAllOfDataModesInner';

/**
 * 
 * @export
 * @interface GetInfoModes200ResponseAllOfData
 */
export interface GetInfoModes200ResponseAllOfData {
    /**
     * Number of available modes.
     * @type {number}
     * @memberof GetInfoModes200ResponseAllOfData
     */
    count?: number;
    /**
     * 
     * @type {Array<GetInfoModes200ResponseAllOfDataModesInner>}
     * @memberof GetInfoModes200ResponseAllOfData
     */
    modes?: Array<GetInfoModes200ResponseAllOfDataModesInner>;
}

/**
 * Check if a given object implements the GetInfoModes200ResponseAllOfData interface.
 */
export function instanceOfGetInfoModes200ResponseAllOfData(value: object): value is GetInfoModes200ResponseAllOfData {
    return true;
}

export function GetInfoModes200ResponseAllOfDataFromJSON(json: any): GetInfoModes200ResponseAllOfData {
    return GetInfoModes200ResponseAllOfDataFromJSONTyped(json, false);
}

export function GetInfoModes200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModes200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'modes': json['modes'] == null ? undefined : ((json['modes'] as Array<any>).map(GetInfoModes200ResponseAllOfDataModesInnerFromJSON)),
    };
}

  export function GetInfoModes200ResponseAllOfDataToJSON(json: any): GetInfoModes200ResponseAllOfData {
      return GetInfoModes200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function GetInfoModes200ResponseAllOfDataToJSONTyped(value?: GetInfoModes200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'modes': value['modes'] == null ? undefined : ((value['modes'] as Array<any>).map(GetInfoModes200ResponseAllOfDataModesInnerToJSON)),
    };
}

