/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetInfoModes200ResponseAllOfDataModesInner
 */
export interface GetInfoModes200ResponseAllOfDataModesInner {
    /**
     * Profile name.
     * @type {string}
     * @memberof GetInfoModes200ResponseAllOfDataModesInner
     */
    profile?: string;
    /**
     * Resolved Ollama model for this profile.
     * @type {string}
     * @memberof GetInfoModes200ResponseAllOfDataModesInner
     */
    model?: string;
    /**
     * Environment variable that configures this profile's model.
     * @type {string}
     * @memberof GetInfoModes200ResponseAllOfDataModesInner
     */
    envVar?: string;
    /**
     * Human-readable summary.
     * @type {string}
     * @memberof GetInfoModes200ResponseAllOfDataModesInner
     */
    description?: string;
}

/**
 * Check if a given object implements the GetInfoModes200ResponseAllOfDataModesInner interface.
 */
export function instanceOfGetInfoModes200ResponseAllOfDataModesInner(value: object): value is GetInfoModes200ResponseAllOfDataModesInner {
    return true;
}

export function GetInfoModes200ResponseAllOfDataModesInnerFromJSON(json: any): GetInfoModes200ResponseAllOfDataModesInner {
    return GetInfoModes200ResponseAllOfDataModesInnerFromJSONTyped(json, false);
}

export function GetInfoModes200ResponseAllOfDataModesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModes200ResponseAllOfDataModesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'] == null ? undefined : json['profile'],
        'model': json['model'] == null ? undefined : json['model'],
        'envVar': json['envVar'] == null ? undefined : json['envVar'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

  export function GetInfoModes200ResponseAllOfDataModesInnerToJSON(json: any): GetInfoModes200ResponseAllOfDataModesInner {
      return GetInfoModes200ResponseAllOfDataModesInnerToJSONTyped(json, false);
  }

  export function GetInfoModes200ResponseAllOfDataModesInnerToJSONTyped(value?: GetInfoModes200ResponseAllOfDataModesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': value['profile'],
        'model': value['model'],
        'envVar': value['envVar'],
        'description': value['description'],
    };
}

