/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { GetInfoModels200ResponseAllOfData } from './GetInfoModels200ResponseAllOfData';
import {
    GetInfoModels200ResponseAllOfDataFromJSON,
    GetInfoModels200ResponseAllOfDataFromJSONTyped,
    GetInfoModels200ResponseAllOfDataToJSON,
    GetInfoModels200ResponseAllOfDataToJSONTyped,
} from './GetInfoModels200ResponseAllOfData';

/**
 * 
 * @export
 * @interface GetInfoModels200Response
 */
export interface GetInfoModels200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetInfoModels200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetInfoModels200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetInfoModels200Response
     */
    message: string;
    /**
     * 
     * @type {GetInfoModels200ResponseAllOfData}
     * @memberof GetInfoModels200Response
     */
    data?: GetInfoModels200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetInfoModels200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetInfoModels200Response interface.
 */
export function instanceOfGetInfoModels200Response(value: object): value is GetInfoModels200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetInfoModels200ResponseFromJSON(json: any): GetInfoModels200Response {
    return GetInfoModels200ResponseFromJSONTyped(json, false);
}

export function GetInfoModels200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModels200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : GetInfoModels200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetInfoModels200ResponseToJSON(json: any): GetInfoModels200Response {
      return GetInfoModels200ResponseToJSONTyped(json, false);
  }

  export function GetInfoModels200ResponseToJSONTyped(value?: GetInfoModels200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': GetInfoModels200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

