/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetInfoModels200ResponseAllOfDataModelsInner } from './GetInfoModels200ResponseAllOfDataModelsInner';
import {
    GetInfoModels200ResponseAllOfDataModelsInnerFromJSON,
    GetInfoModels200ResponseAllOfDataModelsInnerFromJSONTyped,
    GetInfoModels200ResponseAllOfDataModelsInnerToJSON,
    GetInfoModels200ResponseAllOfDataModelsInnerToJSONTyped,
} from './GetInfoModels200ResponseAllOfDataModelsInner';

/**
 * 
 * @export
 * @interface GetInfoModels200ResponseAllOfData
 */
export interface GetInfoModels200ResponseAllOfData {
    /**
     * Number of models available.
     * @type {number}
     * @memberof GetInfoModels200ResponseAllOfData
     */
    count?: number;
    /**
     * The Ollama base URL queried.
     * @type {string}
     * @memberof GetInfoModels200ResponseAllOfData
     */
    ollamaBaseUrl?: string;
    /**
     * 
     * @type {Array<GetInfoModels200ResponseAllOfDataModelsInner>}
     * @memberof GetInfoModels200ResponseAllOfData
     */
    models?: Array<GetInfoModels200ResponseAllOfDataModelsInner>;
}

/**
 * Check if a given object implements the GetInfoModels200ResponseAllOfData interface.
 */
export function instanceOfGetInfoModels200ResponseAllOfData(value: object): value is GetInfoModels200ResponseAllOfData {
    return true;
}

export function GetInfoModels200ResponseAllOfDataFromJSON(json: any): GetInfoModels200ResponseAllOfData {
    return GetInfoModels200ResponseAllOfDataFromJSONTyped(json, false);
}

export function GetInfoModels200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModels200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'ollamaBaseUrl': json['ollamaBaseUrl'] == null ? undefined : json['ollamaBaseUrl'],
        'models': json['models'] == null ? undefined : ((json['models'] as Array<any>).map(GetInfoModels200ResponseAllOfDataModelsInnerFromJSON)),
    };
}

  export function GetInfoModels200ResponseAllOfDataToJSON(json: any): GetInfoModels200ResponseAllOfData {
      return GetInfoModels200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function GetInfoModels200ResponseAllOfDataToJSONTyped(value?: GetInfoModels200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'ollamaBaseUrl': value['ollamaBaseUrl'],
        'models': value['models'] == null ? undefined : ((value['models'] as Array<any>).map(GetInfoModels200ResponseAllOfDataModelsInnerToJSON)),
    };
}

