/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { GetInfoModes200ResponseAllOfData } from './GetInfoModes200ResponseAllOfData';
import {
    GetInfoModes200ResponseAllOfDataFromJSON,
    GetInfoModes200ResponseAllOfDataFromJSONTyped,
    GetInfoModes200ResponseAllOfDataToJSON,
    GetInfoModes200ResponseAllOfDataToJSONTyped,
} from './GetInfoModes200ResponseAllOfData';

/**
 * 
 * @export
 * @interface GetInfoModes200Response
 */
export interface GetInfoModes200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetInfoModes200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetInfoModes200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetInfoModes200Response
     */
    message: string;
    /**
     * 
     * @type {GetInfoModes200ResponseAllOfData}
     * @memberof GetInfoModes200Response
     */
    data?: GetInfoModes200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetInfoModes200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetInfoModes200Response interface.
 */
export function instanceOfGetInfoModes200Response(value: object): value is GetInfoModes200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetInfoModes200ResponseFromJSON(json: any): GetInfoModes200Response {
    return GetInfoModes200ResponseFromJSONTyped(json, false);
}

export function GetInfoModes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : GetInfoModes200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetInfoModes200ResponseToJSON(json: any): GetInfoModes200Response {
      return GetInfoModes200ResponseToJSONTyped(json, false);
  }

  export function GetInfoModes200ResponseToJSONTyped(value?: GetInfoModes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': GetInfoModes200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

