/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportResult } from './ImportResult';
import {
    ImportResultFromJSON,
    ImportResultFromJSONTyped,
    ImportResultToJSON,
    ImportResultToJSONTyped,
} from './ImportResult';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ImportLibrary200Response
 */
export interface ImportLibrary200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ImportLibrary200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof ImportLibrary200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ImportLibrary200Response
     */
    message: string;
    /**
     * 
     * @type {ImportResult}
     * @memberof ImportLibrary200Response
     */
    data?: ImportResult;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ImportLibrary200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the ImportLibrary200Response interface.
 */
export function instanceOfImportLibrary200Response(value: object): value is ImportLibrary200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ImportLibrary200ResponseFromJSON(json: any): ImportLibrary200Response {
    return ImportLibrary200ResponseFromJSONTyped(json, false);
}

export function ImportLibrary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportLibrary200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ImportResultFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function ImportLibrary200ResponseToJSON(json: any): ImportLibrary200Response {
      return ImportLibrary200ResponseToJSONTyped(json, false);
  }

  export function ImportLibrary200ResponseToJSONTyped(value?: ImportLibrary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': ImportResultToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

