/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LintFinding
 */
export interface LintFinding {
    /**
     * Where this finding came from.
     * @type {string}
     * @memberof LintFinding
     */
    source: LintFindingSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof LintFinding
     */
    severity: LintFindingSeverityEnum;
    /**
     * Grouping category (e.g. "typescript", "style", "convention").
     * @type {string}
     * @memberof LintFinding
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof LintFinding
     */
    message: string;
    /**
     * 1-based line number.
     * @type {number}
     * @memberof LintFinding
     */
    line?: number;
    /**
     * 1-based column number.
     * @type {number}
     * @memberof LintFinding
     */
    column?: number;
    /**
     * Machine-readable rule identifier (e.g. "TS2345").
     * @type {string}
     * @memberof LintFinding
     */
    rule?: string;
}


/**
 * @export
 */
export const LintFindingSourceEnum = {
    Typescript: 'typescript',
    Convention: 'convention',
    Llm: 'llm'
} as const;
export type LintFindingSourceEnum = typeof LintFindingSourceEnum[keyof typeof LintFindingSourceEnum];

/**
 * @export
 */
export const LintFindingSeverityEnum = {
    Error: 'error',
    Warning: 'warning',
    Info: 'info'
} as const;
export type LintFindingSeverityEnum = typeof LintFindingSeverityEnum[keyof typeof LintFindingSeverityEnum];


/**
 * Check if a given object implements the LintFinding interface.
 */
export function instanceOfLintFinding(value: object): value is LintFinding {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LintFindingFromJSON(json: any): LintFinding {
    return LintFindingFromJSONTyped(json, false);
}

export function LintFindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LintFinding {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'severity': json['severity'],
        'category': json['category'],
        'message': json['message'],
        'line': json['line'] == null ? undefined : json['line'],
        'column': json['column'] == null ? undefined : json['column'],
        'rule': json['rule'] == null ? undefined : json['rule'],
    };
}

  export function LintFindingToJSON(json: any): LintFinding {
      return LintFindingToJSONTyped(json, false);
  }

  export function LintFindingToJSONTyped(value?: LintFinding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'severity': value['severity'],
        'category': value['category'],
        'message': value['message'],
        'line': value['line'],
        'column': value['column'],
        'rule': value['rule'],
    };
}

