/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Conversation } from './Conversation';
import {
    ConversationFromJSON,
    ConversationFromJSONTyped,
    ConversationToJSON,
    ConversationToJSONTyped,
} from './Conversation';

/**
 * 
 * @export
 * @interface ListConversations200ResponseAllOfData
 */
export interface ListConversations200ResponseAllOfData {
    /**
     * 
     * @type {number}
     * @memberof ListConversations200ResponseAllOfData
     */
    count?: number;
    /**
     * 
     * @type {Array<Conversation>}
     * @memberof ListConversations200ResponseAllOfData
     */
    conversations?: Array<Conversation>;
}

/**
 * Check if a given object implements the ListConversations200ResponseAllOfData interface.
 */
export function instanceOfListConversations200ResponseAllOfData(value: object): value is ListConversations200ResponseAllOfData {
    return true;
}

export function ListConversations200ResponseAllOfDataFromJSON(json: any): ListConversations200ResponseAllOfData {
    return ListConversations200ResponseAllOfDataFromJSONTyped(json, false);
}

export function ListConversations200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConversations200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'conversations': json['conversations'] == null ? undefined : ((json['conversations'] as Array<any>).map(ConversationFromJSON)),
    };
}

  export function ListConversations200ResponseAllOfDataToJSON(json: any): ListConversations200ResponseAllOfData {
      return ListConversations200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function ListConversations200ResponseAllOfDataToJSONTyped(value?: ListConversations200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'conversations': value['conversations'] == null ? undefined : ((value['conversations'] as Array<any>).map(ConversationToJSON)),
    };
}

