/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListConversations200ResponseAllOfData } from './ListConversations200ResponseAllOfData';
import {
    ListConversations200ResponseAllOfDataFromJSON,
    ListConversations200ResponseAllOfDataFromJSONTyped,
    ListConversations200ResponseAllOfDataToJSON,
    ListConversations200ResponseAllOfDataToJSONTyped,
} from './ListConversations200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ListConversations200Response
 */
export interface ListConversations200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListConversations200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListConversations200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListConversations200Response
     */
    message: string;
    /**
     * 
     * @type {ListConversations200ResponseAllOfData}
     * @memberof ListConversations200Response
     */
    data?: ListConversations200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ListConversations200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the ListConversations200Response interface.
 */
export function instanceOfListConversations200Response(value: object): value is ListConversations200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ListConversations200ResponseFromJSON(json: any): ListConversations200Response {
    return ListConversations200ResponseFromJSONTyped(json, false);
}

export function ListConversations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConversations200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ListConversations200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function ListConversations200ResponseToJSON(json: any): ListConversations200Response {
      return ListConversations200ResponseToJSONTyped(json, false);
  }

  export function ListConversations200ResponseToJSONTyped(value?: ListConversations200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': ListConversations200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

