/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LibraryInfo } from './LibraryInfo';
import {
    LibraryInfoFromJSON,
    LibraryInfoFromJSONTyped,
    LibraryInfoToJSON,
    LibraryInfoToJSONTyped,
} from './LibraryInfo';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ListLibraries200Response
 */
export interface ListLibraries200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListLibraries200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListLibraries200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListLibraries200Response
     */
    message: string;
    /**
     * 
     * @type {Array<LibraryInfo>}
     * @memberof ListLibraries200Response
     */
    data?: Array<LibraryInfo>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ListLibraries200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the ListLibraries200Response interface.
 */
export function instanceOfListLibraries200Response(value: object): value is ListLibraries200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ListLibraries200ResponseFromJSON(json: any): ListLibraries200Response {
    return ListLibraries200ResponseFromJSONTyped(json, false);
}

export function ListLibraries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLibraries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(LibraryInfoFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function ListLibraries200ResponseToJSON(json: any): ListLibraries200Response {
      return ListLibraries200ResponseToJSONTyped(json, false);
  }

  export function ListLibraries200ResponseToJSONTyped(value?: ListLibraries200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(LibraryInfoToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

