/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageReviewSuggestion } from './PageReviewSuggestion';
import {
    PageReviewSuggestionFromJSON,
    PageReviewSuggestionFromJSONTyped,
    PageReviewSuggestionToJSON,
    PageReviewSuggestionToJSONTyped,
} from './PageReviewSuggestion';

/**
 * 
 * @export
 * @interface PageReviewCategories
 */
export interface PageReviewCategories {
    /**
     * 
     * @type {Array<PageReviewSuggestion>}
     * @memberof PageReviewCategories
     */
    correctness?: Array<PageReviewSuggestion>;
    /**
     * 
     * @type {Array<PageReviewSuggestion>}
     * @memberof PageReviewCategories
     */
    maintainability?: Array<PageReviewSuggestion>;
    /**
     * 
     * @type {Array<PageReviewSuggestion>}
     * @memberof PageReviewCategories
     */
    standards?: Array<PageReviewSuggestion>;
    /**
     * 
     * @type {Array<PageReviewSuggestion>}
     * @memberof PageReviewCategories
     */
    enhancements?: Array<PageReviewSuggestion>;
}

/**
 * Check if a given object implements the PageReviewCategories interface.
 */
export function instanceOfPageReviewCategories(value: object): value is PageReviewCategories {
    return true;
}

export function PageReviewCategoriesFromJSON(json: any): PageReviewCategories {
    return PageReviewCategoriesFromJSONTyped(json, false);
}

export function PageReviewCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageReviewCategories {
    if (json == null) {
        return json;
    }
    return {
        
        'correctness': json['correctness'] == null ? undefined : ((json['correctness'] as Array<any>).map(PageReviewSuggestionFromJSON)),
        'maintainability': json['maintainability'] == null ? undefined : ((json['maintainability'] as Array<any>).map(PageReviewSuggestionFromJSON)),
        'standards': json['standards'] == null ? undefined : ((json['standards'] as Array<any>).map(PageReviewSuggestionFromJSON)),
        'enhancements': json['enhancements'] == null ? undefined : ((json['enhancements'] as Array<any>).map(PageReviewSuggestionFromJSON)),
    };
}

  export function PageReviewCategoriesToJSON(json: any): PageReviewCategories {
      return PageReviewCategoriesToJSONTyped(json, false);
  }

  export function PageReviewCategoriesToJSONTyped(value?: PageReviewCategories | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correctness': value['correctness'] == null ? undefined : ((value['correctness'] as Array<any>).map(PageReviewSuggestionToJSON)),
        'maintainability': value['maintainability'] == null ? undefined : ((value['maintainability'] as Array<any>).map(PageReviewSuggestionToJSON)),
        'standards': value['standards'] == null ? undefined : ((value['standards'] as Array<any>).map(PageReviewSuggestionToJSON)),
        'enhancements': value['enhancements'] == null ? undefined : ((value['enhancements'] as Array<any>).map(PageReviewSuggestionToJSON)),
    };
}

