/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { PageReviewCategories } from './PageReviewCategories';
import {
    PageReviewCategoriesFromJSON,
    PageReviewCategoriesFromJSONTyped,
    PageReviewCategoriesToJSON,
    PageReviewCategoriesToJSONTyped,
} from './PageReviewCategories';

/**
 * 
 * @export
 * @interface PageReviewResponse
 */
export interface PageReviewResponse {
    /**
     * 
     * @type {string}
     * @memberof PageReviewResponse
     */
    requestId?: string;
    /**
     * The LLM model used.
     * @type {string}
     * @memberof PageReviewResponse
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof PageReviewResponse
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof PageReviewResponse
     */
    filePath?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof PageReviewResponse
     */
    findings?: Array<object>;
    /**
     * 
     * @type {PageReviewCategories}
     * @memberof PageReviewResponse
     */
    categories?: PageReviewCategories;
    /**
     * 
     * @type {number}
     * @memberof PageReviewResponse
     */
    latencyMs?: number;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PageReviewResponse
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PageReviewResponse interface.
 */
export function instanceOfPageReviewResponse(value: object): value is PageReviewResponse {
    return true;
}

export function PageReviewResponseFromJSON(json: any): PageReviewResponse {
    return PageReviewResponseFromJSONTyped(json, false);
}

export function PageReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'model': json['model'] == null ? undefined : json['model'],
        'language': json['language'] == null ? undefined : json['language'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'findings': json['findings'] == null ? undefined : json['findings'],
        'categories': json['categories'] == null ? undefined : PageReviewCategoriesFromJSON(json['categories']),
        'latencyMs': json['latencyMs'] == null ? undefined : json['latencyMs'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PageReviewResponseToJSON(json: any): PageReviewResponse {
      return PageReviewResponseToJSONTyped(json, false);
  }

  export function PageReviewResponseToJSONTyped(value?: PageReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
        'model': value['model'],
        'language': value['language'],
        'filePath': value['filePath'],
        'findings': value['findings'],
        'categories': PageReviewCategoriesToJSON(value['categories']),
        'latencyMs': value['latencyMs'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

