/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageReviewSuggestion
 */
export interface PageReviewSuggestion {
    /**
     * 
     * @type {string}
     * @memberof PageReviewSuggestion
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PageReviewSuggestion
     */
    detail: string;
    /**
     * 
     * @type {number}
     * @memberof PageReviewSuggestion
     */
    priority?: number;
}

/**
 * Check if a given object implements the PageReviewSuggestion interface.
 */
export function instanceOfPageReviewSuggestion(value: object): value is PageReviewSuggestion {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function PageReviewSuggestionFromJSON(json: any): PageReviewSuggestion {
    return PageReviewSuggestionFromJSONTyped(json, false);
}

export function PageReviewSuggestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageReviewSuggestion {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'detail': json['detail'],
        'priority': json['priority'] == null ? undefined : json['priority'],
    };
}

  export function PageReviewSuggestionToJSON(json: any): PageReviewSuggestion {
      return PageReviewSuggestionToJSONTyped(json, false);
  }

  export function PageReviewSuggestionToJSONTyped(value?: PageReviewSuggestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
        'priority': value['priority'],
    };
}

