/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { WorkflowResponse } from './WorkflowResponse';
import {
    WorkflowResponseFromJSON,
    WorkflowResponseFromJSONTyped,
    WorkflowResponseToJSON,
    WorkflowResponseToJSONTyped,
} from './WorkflowResponse';

/**
 * 
 * @export
 * @interface PostWorkflow200Response
 */
export interface PostWorkflow200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostWorkflow200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostWorkflow200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PostWorkflow200Response
     */
    message: string;
    /**
     * 
     * @type {WorkflowResponse}
     * @memberof PostWorkflow200Response
     */
    data?: WorkflowResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PostWorkflow200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PostWorkflow200Response interface.
 */
export function instanceOfPostWorkflow200Response(value: object): value is PostWorkflow200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostWorkflow200ResponseFromJSON(json: any): PostWorkflow200Response {
    return PostWorkflow200ResponseFromJSONTyped(json, false);
}

export function PostWorkflow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWorkflow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : WorkflowResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PostWorkflow200ResponseToJSON(json: any): PostWorkflow200Response {
      return PostWorkflow200ResponseToJSONTyped(json, false);
  }

  export function PostWorkflow200ResponseToJSONTyped(value?: PostWorkflow200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': WorkflowResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

