/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { LintResponse } from './LintResponse';
import {
    LintResponseFromJSON,
    LintResponseFromJSONTyped,
    LintResponseToJSON,
    LintResponseToJSONTyped,
} from './LintResponse';

/**
 * 
 * @export
 * @interface PostLintConventions200Response
 */
export interface PostLintConventions200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostLintConventions200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostLintConventions200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PostLintConventions200Response
     */
    message: string;
    /**
     * 
     * @type {LintResponse}
     * @memberof PostLintConventions200Response
     */
    data?: LintResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PostLintConventions200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PostLintConventions200Response interface.
 */
export function instanceOfPostLintConventions200Response(value: object): value is PostLintConventions200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostLintConventions200ResponseFromJSON(json: any): PostLintConventions200Response {
    return PostLintConventions200ResponseFromJSONTyped(json, false);
}

export function PostLintConventions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLintConventions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : LintResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PostLintConventions200ResponseToJSON(json: any): PostLintConventions200Response {
      return PostLintConventions200ResponseToJSONTyped(json, false);
  }

  export function PostLintConventions200ResponseToJSONTyped(value?: PostLintConventions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': LintResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

