/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageReviewResponse } from './PageReviewResponse';
import {
    PageReviewResponseFromJSON,
    PageReviewResponseFromJSONTyped,
    PageReviewResponseToJSON,
    PageReviewResponseToJSONTyped,
} from './PageReviewResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface PostPageReview200Response
 */
export interface PostPageReview200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostPageReview200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostPageReview200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PostPageReview200Response
     */
    message: string;
    /**
     * 
     * @type {PageReviewResponse}
     * @memberof PostPageReview200Response
     */
    data?: PageReviewResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PostPageReview200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PostPageReview200Response interface.
 */
export function instanceOfPostPageReview200Response(value: object): value is PostPageReview200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostPageReview200ResponseFromJSON(json: any): PostPageReview200Response {
    return PostPageReview200ResponseFromJSONTyped(json, false);
}

export function PostPageReview200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPageReview200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : PageReviewResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PostPageReview200ResponseToJSON(json: any): PostPageReview200Response {
      return PostPageReview200ResponseToJSONTyped(json, false);
  }

  export function PostPageReview200ResponseToJSONTyped(value?: PostPageReview200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': PageReviewResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

