/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { SwarmResponse } from './SwarmResponse';
import {
    SwarmResponseFromJSON,
    SwarmResponseFromJSONTyped,
    SwarmResponseToJSON,
    SwarmResponseToJSONTyped,
} from './SwarmResponse';

/**
 * 
 * @export
 * @interface PostRunSwarm200Response
 */
export interface PostRunSwarm200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostRunSwarm200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostRunSwarm200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PostRunSwarm200Response
     */
    message: string;
    /**
     * 
     * @type {SwarmResponse}
     * @memberof PostRunSwarm200Response
     */
    data?: SwarmResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PostRunSwarm200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PostRunSwarm200Response interface.
 */
export function instanceOfPostRunSwarm200Response(value: object): value is PostRunSwarm200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostRunSwarm200ResponseFromJSON(json: any): PostRunSwarm200Response {
    return PostRunSwarm200ResponseFromJSONTyped(json, false);
}

export function PostRunSwarm200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRunSwarm200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : SwarmResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PostRunSwarm200ResponseToJSON(json: any): PostRunSwarm200Response {
      return PostRunSwarm200ResponseToJSONTyped(json, false);
  }

  export function PostRunSwarm200ResponseToJSONTyped(value?: PostRunSwarm200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': SwarmResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

