/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutocompleteResponse } from './AutocompleteResponse';
import {
    AutocompleteResponseFromJSON,
    AutocompleteResponseFromJSONTyped,
    AutocompleteResponseToJSON,
    AutocompleteResponseToJSONTyped,
} from './AutocompleteResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface PostAutocomplete200Response
 */
export interface PostAutocomplete200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostAutocomplete200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostAutocomplete200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PostAutocomplete200Response
     */
    message: string;
    /**
     * 
     * @type {AutocompleteResponse}
     * @memberof PostAutocomplete200Response
     */
    data?: AutocompleteResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PostAutocomplete200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PostAutocomplete200Response interface.
 */
export function instanceOfPostAutocomplete200Response(value: object): value is PostAutocomplete200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostAutocomplete200ResponseFromJSON(json: any): PostAutocomplete200Response {
    return PostAutocomplete200ResponseFromJSONTyped(json, false);
}

export function PostAutocomplete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAutocomplete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AutocompleteResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PostAutocomplete200ResponseToJSON(json: any): PostAutocomplete200Response {
      return PostAutocomplete200ResponseToJSONTyped(json, false);
  }

  export function PostAutocomplete200ResponseToJSONTyped(value?: PostAutocomplete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': AutocompleteResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

