/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { RunResponse } from './RunResponse';
import {
    RunResponseFromJSON,
    RunResponseFromJSONTyped,
    RunResponseToJSON,
    RunResponseToJSONTyped,
} from './RunResponse';

/**
 * 
 * @export
 * @interface PostRun200Response
 */
export interface PostRun200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostRun200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostRun200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PostRun200Response
     */
    message: string;
    /**
     * 
     * @type {RunResponse}
     * @memberof PostRun200Response
     */
    data?: RunResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof PostRun200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the PostRun200Response interface.
 */
export function instanceOfPostRun200Response(value: object): value is PostRun200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostRun200ResponseFromJSON(json: any): PostRun200Response {
    return PostRun200ResponseFromJSONTyped(json, false);
}

export function PostRun200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRun200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : RunResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function PostRun200ResponseToJSON(json: any): PostRun200Response {
      return PostRun200ResponseToJSONTyped(json, false);
  }

  export function PostRun200ResponseToJSONTyped(value?: PostRun200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': RunResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

