/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ToolCitation } from './ToolCitation';
import {
    ToolCitationFromJSON,
    ToolCitationFromJSONTyped,
    ToolCitationToJSON,
    ToolCitationToJSONTyped,
} from './ToolCitation';

/**
 * 
 * @export
 * @interface RunResponse
 */
export interface RunResponse {
    /**
     * The agent's final answer as a plain string.
     * @type {string}
     * @memberof RunResponse
     */
    result?: string;
    /**
     * 
     * @type {Array<ToolCitation>}
     * @memberof RunResponse
     */
    citations?: Array<ToolCitation>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof RunResponse
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the RunResponse interface.
 */
export function instanceOfRunResponse(value: object): value is RunResponse {
    return true;
}

export function RunResponseFromJSON(json: any): RunResponse {
    return RunResponseFromJSONTyped(json, false);
}

export function RunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'citations': json['citations'] == null ? undefined : ((json['citations'] as Array<any>).map(ToolCitationFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function RunResponseToJSON(json: any): RunResponse {
      return RunResponseToJSONTyped(json, false);
  }

  export function RunResponseToJSONTyped(value?: RunResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'citations': value['citations'] == null ? undefined : ((value['citations'] as Array<any>).map(ToolCitationToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

