/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { RankedArticle } from './RankedArticle';
import {
    RankedArticleFromJSON,
    RankedArticleFromJSONTyped,
    RankedArticleToJSON,
    RankedArticleToJSONTyped,
} from './RankedArticle';

/**
 * 
 * @export
 * @interface SearchLibrary200Response
 */
export interface SearchLibrary200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SearchLibrary200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof SearchLibrary200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof SearchLibrary200Response
     */
    message: string;
    /**
     * 
     * @type {Array<RankedArticle>}
     * @memberof SearchLibrary200Response
     */
    data?: Array<RankedArticle>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof SearchLibrary200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the SearchLibrary200Response interface.
 */
export function instanceOfSearchLibrary200Response(value: object): value is SearchLibrary200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SearchLibrary200ResponseFromJSON(json: any): SearchLibrary200Response {
    return SearchLibrary200ResponseFromJSONTyped(json, false);
}

export function SearchLibrary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchLibrary200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RankedArticleFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function SearchLibrary200ResponseToJSON(json: any): SearchLibrary200Response {
      return SearchLibrary200ResponseToJSONTyped(json, false);
  }

  export function SearchLibrary200ResponseToJSONTyped(value?: SearchLibrary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RankedArticleToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

