/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SseErrorEvent
 */
export interface SseErrorEvent {
    /**
     * 
     * @type {string}
     * @memberof SseErrorEvent
     */
    error?: string;
}

/**
 * Check if a given object implements the SseErrorEvent interface.
 */
export function instanceOfSseErrorEvent(value: object): value is SseErrorEvent {
    return true;
}

export function SseErrorEventFromJSON(json: any): SseErrorEvent {
    return SseErrorEventFromJSONTyped(json, false);
}

export function SseErrorEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseErrorEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function SseErrorEventToJSON(json: any): SseErrorEvent {
      return SseErrorEventToJSONTyped(json, false);
  }

  export function SseErrorEventToJSONTyped(value?: SseErrorEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

