/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SseMaxStepsEvent
 */
export interface SseMaxStepsEvent {
    /**
     * 
     * @type {string}
     * @memberof SseMaxStepsEvent
     */
    task?: string;
    /**
     * 
     * @type {string}
     * @memberof SseMaxStepsEvent
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof SseMaxStepsEvent
     */
    diagnosticFile?: string;
}

/**
 * Check if a given object implements the SseMaxStepsEvent interface.
 */
export function instanceOfSseMaxStepsEvent(value: object): value is SseMaxStepsEvent {
    return true;
}

export function SseMaxStepsEventFromJSON(json: any): SseMaxStepsEvent {
    return SseMaxStepsEventFromJSONTyped(json, false);
}

export function SseMaxStepsEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseMaxStepsEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : json['task'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'diagnosticFile': json['diagnosticFile'] == null ? undefined : json['diagnosticFile'],
    };
}

  export function SseMaxStepsEventToJSON(json: any): SseMaxStepsEvent {
      return SseMaxStepsEventToJSONTyped(json, false);
  }

  export function SseMaxStepsEventToJSONTyped(value?: SseMaxStepsEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': value['task'],
        'summary': value['summary'],
        'diagnosticFile': value['diagnosticFile'],
    };
}

