/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SseRouteEvent
 */
export interface SseRouteEvent {
    /**
     * 
     * @type {string}
     * @memberof SseRouteEvent
     */
    profile?: string;
    /**
     * 
     * @type {string}
     * @memberof SseRouteEvent
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof SseRouteEvent
     */
    reason?: string;
}

/**
 * Check if a given object implements the SseRouteEvent interface.
 */
export function instanceOfSseRouteEvent(value: object): value is SseRouteEvent {
    return true;
}

export function SseRouteEventFromJSON(json: any): SseRouteEvent {
    return SseRouteEventFromJSONTyped(json, false);
}

export function SseRouteEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseRouteEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'] == null ? undefined : json['profile'],
        'model': json['model'] == null ? undefined : json['model'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

  export function SseRouteEventToJSON(json: any): SseRouteEvent {
      return SseRouteEventToJSONTyped(json, false);
  }

  export function SseRouteEventToJSONTyped(value?: SseRouteEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': value['profile'],
        'model': value['model'],
        'reason': value['reason'],
    };
}

