/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SseStepEvent
 */
export interface SseStepEvent {
    /**
     * 
     * @type {number}
     * @memberof SseStepEvent
     */
    step?: number;
    /**
     * 
     * @type {string}
     * @memberof SseStepEvent
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof SseStepEvent
     */
    thought?: string;
}

/**
 * Check if a given object implements the SseStepEvent interface.
 */
export function instanceOfSseStepEvent(value: object): value is SseStepEvent {
    return true;
}

export function SseStepEventFromJSON(json: any): SseStepEvent {
    return SseStepEventFromJSONTyped(json, false);
}

export function SseStepEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseStepEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'] == null ? undefined : json['step'],
        'action': json['action'] == null ? undefined : json['action'],
        'thought': json['thought'] == null ? undefined : json['thought'],
    };
}

  export function SseStepEventToJSON(json: any): SseStepEvent {
      return SseStepEventToJSONTyped(json, false);
  }

  export function SseStepEventToJSONTyped(value?: SseStepEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
        'action': value['action'],
        'thought': value['thought'],
    };
}

