/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SseToolEvent
 */
export interface SseToolEvent {
    /**
     * 
     * @type {string}
     * @memberof SseToolEvent
     */
    tool?: string;
    /**
     * 
     * @type {any}
     * @memberof SseToolEvent
     */
    result?: any | null;
    /**
     * 
     * @type {string}
     * @memberof SseToolEvent
     */
    error?: string;
}

/**
 * Check if a given object implements the SseToolEvent interface.
 */
export function instanceOfSseToolEvent(value: object): value is SseToolEvent {
    return true;
}

export function SseToolEventFromJSON(json: any): SseToolEvent {
    return SseToolEventFromJSONTyped(json, false);
}

export function SseToolEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseToolEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'tool': json['tool'] == null ? undefined : json['tool'],
        'result': json['result'] == null ? undefined : json['result'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function SseToolEventToJSON(json: any): SseToolEvent {
      return SseToolEventToJSONTyped(json, false);
  }

  export function SseToolEventToJSONTyped(value?: SseToolEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool': value['tool'],
        'result': value['result'],
        'error': value['error'],
    };
}

