/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface SuccessEnvelope
 */
export interface SuccessEnvelope {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessEnvelope
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof SuccessEnvelope
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof SuccessEnvelope
     */
    message: string;
    /**
     * 
     * @type {any}
     * @memberof SuccessEnvelope
     */
    data?: any | null;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof SuccessEnvelope
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the SuccessEnvelope interface.
 */
export function instanceOfSuccessEnvelope(value: object): value is SuccessEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SuccessEnvelopeFromJSON(json: any): SuccessEnvelope {
    return SuccessEnvelopeFromJSONTyped(json, false);
}

export function SuccessEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function SuccessEnvelopeToJSON(json: any): SuccessEnvelope {
      return SuccessEnvelopeToJSONTyped(json, false);
  }

  export function SuccessEnvelopeToJSONTyped(value?: SuccessEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': value['data'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

