/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolCitation
 */
export interface ToolCitation {
    /**
     * 
     * @type {string}
     * @memberof ToolCitation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ToolCitation
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ToolCitation
     */
    text: string;
}

/**
 * Check if a given object implements the ToolCitation interface.
 */
export function instanceOfToolCitation(value: object): value is ToolCitation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ToolCitationFromJSON(json: any): ToolCitation {
    return ToolCitationFromJSONTyped(json, false);
}

export function ToolCitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolCitation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'text': json['text'],
    };
}

  export function ToolCitationToJSON(json: any): ToolCitation {
      return ToolCitationToJSONTyped(json, false);
  }

  export function ToolCitationToJSONTyped(value?: ToolCitation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'text': value['text'],
    };
}

