/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConversationRequest
 */
export interface UpdateConversationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateConversationRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateConversationRequest
     */
    profile?: UpdateConversationRequestProfileEnum | null;
}


/**
 * @export
 */
export const UpdateConversationRequestProfileEnum = {
    Fast: 'fast',
    Reasoning: 'reasoning',
    Code: 'code'
} as const;
export type UpdateConversationRequestProfileEnum = typeof UpdateConversationRequestProfileEnum[keyof typeof UpdateConversationRequestProfileEnum];


/**
 * Check if a given object implements the UpdateConversationRequest interface.
 */
export function instanceOfUpdateConversationRequest(value: object): value is UpdateConversationRequest {
    return true;
}

export function UpdateConversationRequestFromJSON(json: any): UpdateConversationRequest {
    return UpdateConversationRequestFromJSONTyped(json, false);
}

export function UpdateConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'profile': json['profile'] == null ? undefined : json['profile'],
    };
}

  export function UpdateConversationRequestToJSON(json: any): UpdateConversationRequest {
      return UpdateConversationRequestToJSONTyped(json, false);
  }

  export function UpdateConversationRequestToJSONTyped(value?: UpdateConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'profile': value['profile'],
    };
}

