/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMessageRequest
 */
export interface UpdateMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateMessageRequest
     */
    content: string;
}

/**
 * Check if a given object implements the UpdateMessageRequest interface.
 */
export function instanceOfUpdateMessageRequest(value: object): value is UpdateMessageRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UpdateMessageRequestFromJSON(json: any): UpdateMessageRequest {
    return UpdateMessageRequestFromJSONTyped(json, false);
}

export function UpdateMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

  export function UpdateMessageRequestToJSON(json: any): UpdateMessageRequest {
      return UpdateMessageRequestToJSONTyped(json, false);
  }

  export function UpdateMessageRequestToJSONTyped(value?: UpdateMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

