/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadImageClassify200ResponseAllOfData
 */
export interface UploadImageClassify200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof UploadImageClassify200ResponseAllOfData
     */
    model?: string;
    /**
     * The model's textual description of the image.
     * @type {string}
     * @memberof UploadImageClassify200ResponseAllOfData
     */
    response?: string;
}

/**
 * Check if a given object implements the UploadImageClassify200ResponseAllOfData interface.
 */
export function instanceOfUploadImageClassify200ResponseAllOfData(value: object): value is UploadImageClassify200ResponseAllOfData {
    return true;
}

export function UploadImageClassify200ResponseAllOfDataFromJSON(json: any): UploadImageClassify200ResponseAllOfData {
    return UploadImageClassify200ResponseAllOfDataFromJSONTyped(json, false);
}

export function UploadImageClassify200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImageClassify200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'response': json['response'] == null ? undefined : json['response'],
    };
}

  export function UploadImageClassify200ResponseAllOfDataToJSON(json: any): UploadImageClassify200ResponseAllOfData {
      return UploadImageClassify200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function UploadImageClassify200ResponseAllOfDataToJSONTyped(value?: UploadImageClassify200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'response': value['response'],
    };
}

