/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadReadPdf200ResponseAllOfData } from './UploadReadPdf200ResponseAllOfData';
import {
    UploadReadPdf200ResponseAllOfDataFromJSON,
    UploadReadPdf200ResponseAllOfDataFromJSONTyped,
    UploadReadPdf200ResponseAllOfDataToJSON,
    UploadReadPdf200ResponseAllOfDataToJSONTyped,
} from './UploadReadPdf200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface UploadReadPdf200Response
 */
export interface UploadReadPdf200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UploadReadPdf200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof UploadReadPdf200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof UploadReadPdf200Response
     */
    message: string;
    /**
     * 
     * @type {UploadReadPdf200ResponseAllOfData}
     * @memberof UploadReadPdf200Response
     */
    data?: UploadReadPdf200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof UploadReadPdf200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the UploadReadPdf200Response interface.
 */
export function instanceOfUploadReadPdf200Response(value: object): value is UploadReadPdf200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UploadReadPdf200ResponseFromJSON(json: any): UploadReadPdf200Response {
    return UploadReadPdf200ResponseFromJSONTyped(json, false);
}

export function UploadReadPdf200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadReadPdf200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UploadReadPdf200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function UploadReadPdf200ResponseToJSON(json: any): UploadReadPdf200Response {
      return UploadReadPdf200ResponseToJSONTyped(json, false);
  }

  export function UploadReadPdf200ResponseToJSONTyped(value?: UploadReadPdf200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': UploadReadPdf200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

