/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadImageClassify200ResponseAllOfData } from './UploadImageClassify200ResponseAllOfData';
import {
    UploadImageClassify200ResponseAllOfDataFromJSON,
    UploadImageClassify200ResponseAllOfDataFromJSONTyped,
    UploadImageClassify200ResponseAllOfDataToJSON,
    UploadImageClassify200ResponseAllOfDataToJSONTyped,
} from './UploadImageClassify200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface UploadImageClassify200Response
 */
export interface UploadImageClassify200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UploadImageClassify200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof UploadImageClassify200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof UploadImageClassify200Response
     */
    message: string;
    /**
     * 
     * @type {UploadImageClassify200ResponseAllOfData}
     * @memberof UploadImageClassify200Response
     */
    data?: UploadImageClassify200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof UploadImageClassify200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the UploadImageClassify200Response interface.
 */
export function instanceOfUploadImageClassify200Response(value: object): value is UploadImageClassify200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UploadImageClassify200ResponseFromJSON(json: any): UploadImageClassify200Response {
    return UploadImageClassify200ResponseFromJSONTyped(json, false);
}

export function UploadImageClassify200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImageClassify200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UploadImageClassify200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function UploadImageClassify200ResponseToJSON(json: any): UploadImageClassify200Response {
      return UploadImageClassify200ResponseToJSONTyped(json, false);
  }

  export function UploadImageClassify200ResponseToJSONTyped(value?: UploadImageClassify200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': UploadImageClassify200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

