/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadReadPdf200ResponseAllOfData
 */
export interface UploadReadPdf200ResponseAllOfData {
    /**
     * Full extracted text
     * @type {string}
     * @memberof UploadReadPdf200ResponseAllOfData
     */
    text?: string;
    /**
     * Total number of pages in the PDF
     * @type {number}
     * @memberof UploadReadPdf200ResponseAllOfData
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the UploadReadPdf200ResponseAllOfData interface.
 */
export function instanceOfUploadReadPdf200ResponseAllOfData(value: object): value is UploadReadPdf200ResponseAllOfData {
    return true;
}

export function UploadReadPdf200ResponseAllOfDataFromJSON(json: any): UploadReadPdf200ResponseAllOfData {
    return UploadReadPdf200ResponseAllOfDataFromJSONTyped(json, false);
}

export function UploadReadPdf200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadReadPdf200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'pageCount': json['pageCount'] == null ? undefined : json['pageCount'],
    };
}

  export function UploadReadPdf200ResponseAllOfDataToJSON(json: any): UploadReadPdf200ResponseAllOfData {
      return UploadReadPdf200ResponseAllOfDataToJSONTyped(json, false);
  }

  export function UploadReadPdf200ResponseAllOfDataToJSONTyped(value?: UploadReadPdf200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'pageCount': value['pageCount'],
    };
}

