/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ImageProcessorResponse } from './ImageProcessorResponse';
import {
    ImageProcessorResponseFromJSON,
    ImageProcessorResponseFromJSONTyped,
    ImageProcessorResponseToJSON,
    ImageProcessorResponseToJSONTyped,
} from './ImageProcessorResponse';

/**
 * 
 * @export
 * @interface UploadImageSketch200Response
 */
export interface UploadImageSketch200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UploadImageSketch200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof UploadImageSketch200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof UploadImageSketch200Response
     */
    message: string;
    /**
     * 
     * @type {ImageProcessorResponse}
     * @memberof UploadImageSketch200Response
     */
    data?: ImageProcessorResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof UploadImageSketch200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the UploadImageSketch200Response interface.
 */
export function instanceOfUploadImageSketch200Response(value: object): value is UploadImageSketch200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UploadImageSketch200ResponseFromJSON(json: any): UploadImageSketch200Response {
    return UploadImageSketch200ResponseFromJSONTyped(json, false);
}

export function UploadImageSketch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImageSketch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ImageProcessorResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function UploadImageSketch200ResponseToJSON(json: any): UploadImageSketch200Response {
      return UploadImageSketch200ResponseToJSONTyped(json, false);
  }

  export function UploadImageSketch200ResponseToJSONTyped(value?: UploadImageSketch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': ImageProcessorResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

