/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadSpeechToText200ResponseAllOfData } from './UploadSpeechToText200ResponseAllOfData';
import {
    UploadSpeechToText200ResponseAllOfDataFromJSON,
    UploadSpeechToText200ResponseAllOfDataFromJSONTyped,
    UploadSpeechToText200ResponseAllOfDataToJSON,
    UploadSpeechToText200ResponseAllOfDataToJSONTyped,
} from './UploadSpeechToText200ResponseAllOfData';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface UploadSpeechToText200Response
 */
export interface UploadSpeechToText200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UploadSpeechToText200Response
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof UploadSpeechToText200Response
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof UploadSpeechToText200Response
     */
    message: string;
    /**
     * 
     * @type {UploadSpeechToText200ResponseAllOfData}
     * @memberof UploadSpeechToText200Response
     */
    data?: UploadSpeechToText200ResponseAllOfData;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof UploadSpeechToText200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the UploadSpeechToText200Response interface.
 */
export function instanceOfUploadSpeechToText200Response(value: object): value is UploadSpeechToText200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UploadSpeechToText200ResponseFromJSON(json: any): UploadSpeechToText200Response {
    return UploadSpeechToText200ResponseFromJSONTyped(json, false);
}

export function UploadSpeechToText200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSpeechToText200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UploadSpeechToText200ResponseAllOfDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function UploadSpeechToText200ResponseToJSON(json: any): UploadSpeechToText200Response {
      return UploadSpeechToText200ResponseToJSONTyped(json, false);
  }

  export function UploadSpeechToText200ResponseToJSONTyped(value?: UploadSpeechToText200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status': value['status'],
        'message': value['message'],
        'data': UploadSpeechToText200ResponseAllOfDataToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

